﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace DailyDairyAuto
{
    public partial class MLModelMilk
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"pH", @"pH"),new InputOutputColumnPair(@"Temprature", @"Temprature"),new InputOutputColumnPair(@"Fat", @"Fat"),new InputOutputColumnPair(@"Turbidity", @"Turbidity"),new InputOutputColumnPair(@"Colour", @"Colour")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"pH",@"Temprature",@"Fat",@"Turbidity",@"Colour"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Grade",inputColumnName:@"Grade"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LightGbm(new LightGbmMulticlassTrainer.Options(){NumberOfLeaves=9,NumberOfIterations=18,MinimumExampleCountPerLeaf=20,LearningRate=0.999999776672986,LabelColumnName=@"Grade",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.501331555417875,FeatureFraction=0.99999999,L1Regularization=2E-10,L2Regularization=0.999999776672986},MaximumBinCountPerFeature=62}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
