// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace DailyDairyAuto
{
    public partial class MLModelCattle
    {
        /// <summary>
        /// model input class for MLModelCattle.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"body_temperature")]
            public float Body_temperature { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"breed_type")]
            public string Breed_type { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"milk_production")]
            public float Milk_production { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"respiratory_rate")]
            public float Respiratory_rate { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"walking_capacity")]
            public float Walking_capacity { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"sleeping_duration")]
            public float Sleeping_duration { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"body_condition_score")]
            public float Body_condition_score { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"heart_rate")]
            public float Heart_rate { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"eating_duration")]
            public float Eating_duration { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"lying_down_duration")]
            public float Lying_down_duration { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"ruminating")]
            public float Ruminating { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"rumen_fill")]
            public float Rumen_fill { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"health_status")]
            public string Health_status { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelCattle.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"body_temperature")]
            public float Body_temperature { get; set; }

            [ColumnName(@"breed_type")]
            public float[] Breed_type { get; set; }

            [ColumnName(@"milk_production")]
            public float Milk_production { get; set; }

            [ColumnName(@"respiratory_rate")]
            public float Respiratory_rate { get; set; }

            [ColumnName(@"walking_capacity")]
            public float Walking_capacity { get; set; }

            [ColumnName(@"sleeping_duration")]
            public float Sleeping_duration { get; set; }

            [ColumnName(@"body_condition_score")]
            public float Body_condition_score { get; set; }

            [ColumnName(@"heart_rate")]
            public float Heart_rate { get; set; }

            [ColumnName(@"eating_duration")]
            public float Eating_duration { get; set; }

            [ColumnName(@"lying_down_duration")]
            public float Lying_down_duration { get; set; }

            [ColumnName(@"ruminating")]
            public float Ruminating { get; set; }

            [ColumnName(@"rumen_fill")]
            public float Rumen_fill { get; set; }

            [ColumnName(@"health_status")]
            public uint Health_status { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModelCattle.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("health_status");
            if (labelColumn == null)
            {
                throw new Exception("health_status column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
