// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace DailyDairyAuto
{
    public partial class MLModelMilk
    {
        /// <summary>
        /// model input class for MLModelMilk.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"pH")]
            public float PH { get; set; }

            [ColumnName(@"Temprature")]
            public float Temprature { get; set; }

            [ColumnName(@"Fat")]
            public float Fat { get; set; }

            [ColumnName(@"Turbidity")]
            public float Turbidity { get; set; }

            [ColumnName(@"Colour")]
            public float Colour { get; set; }

            [ColumnName(@"Grade")]
            public string Grade { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelMilk.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"pH")]
            public float PH { get; set; }

            [ColumnName(@"Temprature")]
            public float Temprature { get; set; }

            [ColumnName(@"Fat")]
            public float Fat { get; set; }

            [ColumnName(@"Turbidity")]
            public float Turbidity { get; set; }

            [ColumnName(@"Colour")]
            public float Colour { get; set; }

            [ColumnName(@"Grade")]
            public uint Grade { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModelMilk.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
